server:
  port: 9500
spring:
  application:
    name: oauth2-custom

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:secret}
  expiration: ${JWT_EXPIRATION:86400000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:}604800000
clients:
  users-service: ${USER_URL:http://localhost:8080/v1/users}
